"""
Interview questions aimed at what the resume could not tell us.

The system already knows, per candidate, which skills are stated, which are
demonstrated without being named, which are claimed without support and which are
absent. That is exactly the information needed to stop asking "so, do you know
Docker?" — a question whose answer is already on the page, and which a candidate
answers yes to regardless.

Four kinds of question, in the order they are worth asking:

    GAP          a required skill they do not have. Asks how they would approach
                 it from the thing they DO have, which is a real signal: it tests
                 transfer rather than recall.

    CLAIM        a skill they list with nothing behind it — no project on the
                 resume, no code in the repositories. The question is deliberately
                 open and non-accusatory; it gives an honest candidate an easy
                 answer and gives a padded resume nowhere to go.

    INFERRED     a skill the semantic channel found that they never named. Worth
                 confirming, because if it is real this candidate is underrated by
                 every keyword filter they will ever meet.

    PROJECT      grounded in a repository they actually pushed, by name.

Every question carries the evidence that motivated it, so the interviewer can see
why they are being asked to ask it. Nothing here is generated by a language model
— the templates are in `backend/data/coaching.json` and the selection is driven
by the evidence matrix.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from functools import lru_cache

from backend import config
from backend.core import taxonomy
from backend.core.enrich import Enrichment
from backend.core.fusion import Candidate, INFERRED, MATCHED, MISSING, WEAK
from backend.core.skills import REQUIRED

GAP = "GAP"
CLAIM = "CLAIM"
INFERRED_Q = "INFERRED"
PROJECT = "PROJECT"


@lru_cache(maxsize=1)
def _coaching() -> dict:
    return json.loads(config.COACHING_PATH.read_text(encoding="utf-8"))


def probe_for(skill_id: str, cluster: str) -> str:
    """The interview probe for a skill, falling back to its cluster."""
    entry = _coaching()["skills"].get(skill_id)
    if entry:
        return entry["probe"]
    fallback = _coaching()["clusters"].get(cluster) or _coaching()["clusters"]["Other"]
    return fallback["probe"]


@dataclass(slots=True)
class Question:
    kind: str
    skill_id: str
    skill_label: str
    question: str
    why: str                    # what in the evidence prompted this
    evidence: str = ""          # the resume line or repository behind it
    bridge: str = ""            # the adjacency the question leans on
    path: list[str] = field(default_factory=list)


@dataclass(slots=True)
class InterviewGuide:
    doc_id: str
    name: str
    rank: int
    questions: list[Question] = field(default_factory=list)
    headline: str = ""


def _held(cand: Candidate) -> dict[str, float]:
    strength = {MATCHED: 1.0, INFERRED: 0.75, WEAK: 0.4}
    return {c.skill_id: strength[c.status]
            for c in cand.primitives.cells if c.status in strength}


def _difficulty(skill_id: str) -> int:
    """How much of a mental model this skill is. Unknown skills sit mid-scale."""
    node = taxonomy.skills().get(skill_id)
    return node["difficulty"] if node else 3


# Below this, a skill is table stakes rather than a differentiator, and an
# unsupported claim about it is not worth an interview question.
PROBE_MIN_DIFFICULTY = 3


def _worth_probing(cell) -> bool:
    """Is an unsupported claim about this skill worth asking about?"""
    if cell.tier != REQUIRED:
        return False
    # A claim the candidate's own code contradicts is always worth one question,
    # however ordinary the skill.
    if cell.external_verdict == "CONTRADICTED":
        return True
    return _difficulty(cell.skill_id) >= PROBE_MIN_DIFFICULTY


def _label(cand: Candidate, skill_id: str | None) -> str:
    if not skill_id:
        return ""
    for c in cand.primitives.cells:
        if c.skill_id == skill_id:
            return c.label
    return skill_id


def for_candidate(cand: Candidate, enrichment: Enrichment | None = None,
                  limit: int = 3) -> InterviewGuide:
    """Build a short, targeted interview guide for one shortlisted candidate."""
    guide = InterviewGuide(doc_id=cand.doc_id, name=cand.name, rank=cand.rank)
    cells = cand.primitives.cells
    held = _held(cand)

    # --- 1. Required gaps, hardest first --------------------------------------
    gaps = sorted(
        (c for c in cells if c.status in (MISSING, WEAK) and c.tier == REQUIRED),
        key=lambda c: (-c.weight, c.coverage),
    )
    for cell in gaps[:2]:
        springboards = {k: v for k, v in held.items() if k != cell.skill_id}
        bridge = taxonomy.bridge(cell.skill_id, springboards, cell.label)
        from_label = _label(cand, bridge.springboard)

        base = probe_for(cell.skill_id, cell.cluster)
        if from_label:
            question = (f"They have {from_label} but not {cell.label}. "
                        f"Ask: “{base}”")
            why = (f"{cell.label} is required and missing; {from_label} is the closest "
                   f"thing they have ({bridge.human} to bridge). The answer shows whether "
                   f"they can transfer, which the resume cannot.")
        else:
            question = f"Ask: “{base}”"
            why = (f"{cell.label} is required and nothing on the resume sits near it. "
                   f"Worth establishing how they would start.")

        guide.questions.append(Question(
            kind=GAP, skill_id=cell.skill_id, skill_label=cell.label,
            question=question, why=why, evidence=cell.evidence,
            bridge=from_label, path=taxonomy.path_labels(cell.skill_id, cell.label),
        ))

    # --- 2. Unsupported or contradicted claims --------------------------------
    # Only claims worth spending an interview slot on. An orphan "HTML" or "Git"
    # is technically an unsupported claim and tells an interviewer nothing —
    # everybody lists them, and the answer is never the reason anyone is hired or
    # not. Probing needs a skill that actually discriminates between candidates.
    suspect = [
        c for c in cells
        if c.lex > 0.0
        and (c.external_verdict == "CONTRADICTED" or c.integrity_mult < 1.0)
        and _worth_probing(c)
    ]
    # Contradicted by code first — that is the stronger signal — then by how much
    # of a mental model the skill represents.
    suspect.sort(key=lambda c: (
        c.external_verdict != "CONTRADICTED",
        -_difficulty(c.skill_id),
        -c.weight,
        c.label.lower(),
    ))
    for cell in suspect[:2]:
        reason = ("it appears in no public repository"
                  if cell.external_verdict == "CONTRADICTED"
                  else "it appears only in their skills list, with no project behind it")
        guide.questions.append(Question(
            kind=CLAIM, skill_id=cell.skill_id, skill_label=cell.label,
            question=(f"They list {cell.label} but {reason}. "
                      f"Ask: “Tell me about the last thing you built with {cell.label} — "
                      f"what did you use it for, and what went wrong?”"),
            why=("An open question, not an accusation: a real project produces a specific "
                 "answer immediately, and a padded line does not."),
            evidence=cell.evidence,
        ))

    # --- 3. Skills demonstrated but never named -------------------------------
    inferred = sorted(
        (c for c in cells if c.status == INFERRED and c.tier == REQUIRED),
        key=lambda c: -c.sem_raw,
    )
    for cell in inferred[:1]:
        guide.questions.append(Question(
            kind=INFERRED_Q, skill_id=cell.skill_id, skill_label=cell.label,
            question=(f"They never write “{cell.label}”, but their experience reads like it. "
                      f"Ask: “{probe_for(cell.skill_id, cell.cluster)}”"),
            why=(f"The semantic channel matched this at {cell.sem_raw:.2f} cosine without a "
                 f"literal mention. If it holds up, every keyword filter is underrating them."),
            evidence=cell.evidence,
        ))

    # --- 4. Grounded in their actual repositories -----------------------------
    if enrichment and enrichment.github.ok and enrichment.github.repos:
        repo = max(enrichment.github.repos,
                   key=lambda r: (len(r.code_skills), r.stars))
        readme_only = repo.readme_only
        if readme_only:
            claimed = ", ".join(readme_only[:3])
            guide.questions.append(Question(
                kind=PROJECT, skill_id="", skill_label=repo.name,
                question=(f"Their repository “{repo.name}” advertises {claimed} in its README, "
                          f"but the manifest shows none of it. "
                          f"Ask: “Walk me through how {repo.name} is actually deployed today.”"),
                why=("A README describing an architecture the code does not contain is worth "
                     "one question — it is usually ambition rather than dishonesty, and the "
                     "answer distinguishes them."),
                evidence=f"{repo.name}: {repo.description}".strip(": "),
            ))
        elif repo.code_skills:
            stack = ", ".join(repo.code_skills[:3])
            guide.questions.append(Question(
                kind=PROJECT, skill_id="", skill_label=repo.name,
                question=(f"Ask: “In {repo.name} you used {stack}. What was the hardest "
                          f"decision in that project, and what would you change now?”"),
                why=("Grounded in code they actually pushed, so it cannot be answered from "
                     "a memorised script."),
                evidence=f"{repo.name}: {repo.description}".strip(": "),
            ))

    guide.questions = guide.questions[:max(limit, 1)]
    guide.headline = _headline(guide, cand)
    return guide


def _headline(guide: InterviewGuide, cand: Candidate) -> str:
    kinds = {q.kind for q in guide.questions}
    if not guide.questions:
        return "No targeted questions — this candidate matches the JD on every axis tested."
    parts = []
    if GAP in kinds:
        parts.append("probe the gaps")
    if CLAIM in kinds:
        parts.append("test the unsupported claims")
    if INFERRED_Q in kinds:
        parts.append("confirm what they never named")
    if PROJECT in kinds:
        parts.append("go into their code")
    return f"{len(guide.questions)} questions to " + ", ".join(parts) + "."


def top(candidates: list[Candidate],
        enrichments: dict[str, Enrichment] | None = None,
        n: int | None = None, per_candidate: int = 3) -> list[InterviewGuide]:
    """Interview guides for the shortlist."""
    limit = config.RAMPUP_TOP_N if n is None else n
    ext = enrichments or {}
    return [
        for_candidate(c, ext.get(c.doc_id), limit=per_candidate)
        for c in candidates[:limit]
    ]
